name: Android Build

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Checkout submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.ACTION_TOKEN }}

    - name: Set TMDB API Key
      run: echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> local.properties

    - name: Check spotless
      run: ./gradlew spotlessCheck --init-script gradle/init.gradle.kts --no-configuration-cache

    - name: Run detekt
      run: ./gradlew detekt
      
    - name: Build with Gradle
      run: ./gradlew build
